ORIGINAL_SONGS_ROOT_PATH = r"..\resources\songs"
ORIGINAL_SONGS_EXTENSION = ".json"
SONGS_FILENAME_TEMPLATE = r"..\storage\files\songs\song_%s.json"
ALBUMS_FILENAME_TEMPLATE = r"..\storage\files\albums\album_%s.json"
ARTISTS_FILENAME_TEMPLATE = r"..\storage\files\artists\artist_%s.json"
USERS_FILENAME_TEMPLATE = r"..\storage\files\users\user_%s.json"
